name: 使用 Hugging Face SDK 创建 Player Space

on:
  workflow_dispatch:
    inputs:
      Token:
        description: 'Hugging Face Access Token（需要写权限）'
        required: true
        default: ''
      UserID:
        description: '你的 Hugging Face 用户名'
        required: true
        default: ''
      SpaceName:
        description: 'Space 名称（默认：Player）'
        required: false
        default: 'Player'
      Private:
        description: '是否设为私有 Space（true/false）'
        required: false
        default: 'false'

jobs:
  create-space:
    runs-on: ubuntu-latest

    steps:
      - name: 克隆 Player 仓库
        run: |
          git clone https://github.com/zxlwq/Player.git
          ls Player

      - name: 安装 Python 与 Hugging Face SDK
        run: |
          python3 -m pip install --upgrade pip
          pip install huggingface_hub

      - name: 创建 Hugging Face Space 并上传代码
        run: |
          python3 <<EOF
from huggingface_hub import HfApi
import os

token = "${{ github.event.inputs.Token }}"
user = "${{ github.event.inputs.UserID }}"
space_name = "${{ github.event.inputs.SpaceName }}" or "Player"
private = "${{ github.event.inputs.Private }}".lower() == "true"

repo_id = f"{user}/{space_name}"
api = HfApi()

try:
    api.create_repo(
        repo_id=repo_id,
        token=token,
        repo_type="space",
        space_sdk="static",
        private=private
    )
    print(f"✅ 成功创建 Space：{repo_id}")
except Exception as e:
    print(f"⚠️ Space 创建失败（可能已存在）：{e}")

try:
    api.upload_folder(
        folder_path="Player",
        repo_id=repo_id,
        repo_type="space",
        token=token
    )
    print("✅ Player 代码上传完成。")
except Exception as e:
    print(f"❌ 上传失败：{e}")
EOF
