name: 部署Player

on:
  workflow_dispatch:
    inputs:
      HfToken:
        description: 'Hugging Face Token (写权限)'
        required: true
      HfUsername:
        description: 'Hugging Face 用户名或组织'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 安装依赖
        run: |
          python3 -m pip install --upgrade pip
          pip install huggingface_hub requests

      - name: 生成随机Space名称
        id: gen_space_name
        run: |
          SPACE_NAME=$(cat /dev/urandom | tr -dc 'A-Z' | head -c 1)
          echo "space_name=$SPACE_NAME" >> $GITHUB_OUTPUT

      - name: 运行部署脚本
        run: |
          python3 player.py \
            --hf_token "${{ github.event.inputs.HfToken }}" \
            --hf_user "${{ github.event.inputs.HfUsername }}" \
            --space_name "${{ steps.gen_space_name.outputs.space_name }}"
