name: Deploy to Hugging Face Space

on:
  workflow_dispatch:
    inputs:
      hf_token:
        description: 'Hugging Face Access Token（需要写权限）'
        required: true
      hf_user:
        description: 'Hugging Face 用户名'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 下载 player.py 文件
        run: |
          curl -o player.py https://raw.githubusercontent.com/zxlwq/Player/main/player.py

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 安装依赖 huggingface_hub
        run: pip install huggingface_hub requests

      - name: 执行部署脚本（自动分配 Space 名）
        run: |
          python3 player.py \
            --hf_token "${{ github.event.inputs.hf_token }}" \
            --hf_user "${{ github.event.inputs.hf_user }}"
