name: 使用抱脸SDK创建Player

on:
  workflow_dispatch:
    inputs:
      Token:
        description: 'HuggingFace 的 Access Token，需具有写入 Spaces 权限'
        required: true
        default: ''
      UserID:
        description: 'HuggingFace 用户名'
        required: true
        default: ''
      SpaceName:
        description: 'Spaces 名称（可选，不填默认为 Player）'
        required: false
        default: 'Player'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v3

      - name: 隐藏敏感输入
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name:
        env:
          HF_TOKEN: ${{ github.event.inputs.Token }}
          HF_USER: ${{ github.event.inputs.UserID }}
          HF_SPACE: ${{ github.event.inputs.SpaceName }}
        run: |
          python <<EOF
          from huggingface_hub import HfApi
          import os
          import subprocess

          token = os.environ["HF_TOKEN"]
          user = os.environ["HF_USER"]
          space_name = os.environ.get("HF_SPACE", "Player")
          full_space_id = f"{user}/{space_name}"

          api = HfApi(token=token)

          print(f"🚀 正在强制创建 Space：{full_space_id}")
          api.create_repo(
              repo_id=full_space_id,
              repo_type="space",
              space_sdk="docker",
              private=False,
              exist_ok=True
          )

          # 初始化 Git 并强推代码
          subprocess.run(["git", "init"])
          subprocess.run(["git", "config", "--global", "user.name", "github-actions"])
          subprocess.run(["git", "config", "--global", "user.email", "actions@github.com"])
          subprocess.run(["git", "remote", "add", "origin", f"https://{token}@huggingface.co/spaces/{full_space_id}"])
          subprocess.run(["git", "add", "."])
          subprocess.run(["git", "commit", "-m", "🤖 自动部署 Player 项目到 Hugging Face"])
          subprocess.run(["git", "push", "--force", "origin", "HEAD:main"])
          EOF
