name: Deploy to Hugging Face Space

on:
  workflow_dispatch:
    inputs:
      hf_token:
        description: 'Hugging Face Token'
        required: true
      hf_user:
        description: 'Hugging Face Username'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Download player.py only
        run: |
          curl -o player.py https://raw.githubusercontent.com/zxlwq/Player/main/player.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install huggingface_hub requests

      - name: Run player.py
        run: |
          python3 player.py \
            --hf_token "${{ github.event.inputs.hf_token }}" \
            --hf_user "${{ github.event.inputs.hf_user }}"
