name: 推送Docker镜像

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker 镜像标签"
        required: false
        default: "latest"
      push_dockerhub:
        description: "是否推送到 Docker Hub"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 登录 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 登录 Docker Hub
        if: ${{ github.event.inputs.push_dockerhub }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/zxlwq/music:${{ github.event.inputs.tag }}
            ${{ github.event.inputs.push_dockerhub && format('docker.io/{0}/music:{1}', secrets.DOCKER_HUB_USERNAME, github.event.inputs.tag) }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=music Docker 镜像
            org.opencontainers.image.licenses=MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
