name: 使用抱脸SDK创建音乐播放器

on:
  workflow_dispatch:
    inputs:
      Token:
        description: '抱脸的Token,需要写权限'
        required: true
        default: ''
      Image:
        description: 'docker镜像地址'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: 隐藏输入信息
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: 检查系统依赖
        run: |
          python -V

      - name: 安装所需依赖
        run: |
          python -m pip install --upgrade pip wheel
          pip install huggingface_hub

      - name: 运行脚本
        run: |
          python player.py \
            --token "${{ github.event.inputs.Token }}" \
            --image "${{ github.event.inputs.Image }}"
