name: Run Player Script

on:
  workflow_dispatch:
    inputs:
      hf_token:
        description: 'HuggingFace Token'
        required: true
        type: string
      hf_user:
        description: 'HuggingFace Username'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download player.py
        run: |
          curl -sSL -o player.py https://raw.githubusercontent.com/zxlwq/Player/main/player.py

      - name: Install dependencies
        run: |
          pip install huggingface_hub requests

      - name: Run player.py
        run: |
          python3 player.py \
            --hf_token "${{ github.event.inputs.hf_token }}" \
            --hf_user "${{ github.event.inputs.hf_user }}"
